#!/usr/bin/env node
// build_agent_config.mjs — merge every chains/*/chain.yaml into a
// single shared/agent-config.json that the Hyperlane agents mount.
//
// drive.sh runs this before every `up`, so the agent always boots with
// a fresh consolidated config. Idempotent — same input == same output.
//
// Source: every chains/<key>/chain.yaml under the kit root.
// Output: shared/agent-config.json
//
// Skips chains/_template/ (the blueprint, not a real chain).

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { parse as parseYaml } from 'yaml';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const KIT_ROOT = path.resolve(__dirname, '..');
const CHAINS_DIR = path.join(KIT_ROOT, 'chains');
const OUT_PATH = path.join(KIT_ROOT, 'shared', 'agent-config.json');

function readChain(dir) {
  const yamlPath = path.join(dir, 'chain.yaml');
  if (!fs.existsSync(yamlPath)) return null;
  const c = parseYaml(fs.readFileSync(yamlPath, 'utf8'));
  if (!c || !c.key) return null;
  return c;
}

function toAgentEntry(c) {
  const entry = {
    name: c.key,
    chainId: c.chainId,
    domainId: c.domain ?? c.chainId,
    protocol: c.protocol || 'ethereum',
    rpcUrls: (c.rpcUrls || []).map(u => ({ http: u })),
    mailbox: c.hyperlane?.mailbox || '0x0000000000000000000000000000000000000000',
    merkleTreeHook: c.hyperlane?.merkleTreeHook || '0x0000000000000000000000000000000000000000',
    interchainGasPaymaster: '0x0000000000000000000000000000000000000000',
    validatorAnnounce: c.hyperlane?.validatorAnnounce || '0x0000000000000000000000000000000000000000',
    index: {
      from: c.index?.from ?? 1,
      chunk: c.index?.chunk ?? 2000,
    },
    reorgPeriod: c.finality?.reorgPeriod ?? 5,
  };

  // Cosmos chains need chainId/domainId as STRINGS (agent quirk).
  if (entry.protocol === 'cosmosnative') {
    entry.chainId = String(entry.chainId);
    entry.domainId = String(entry.domainId);
    if (c.bech32Prefix) entry.bech32Prefix = c.bech32Prefix;
    if (c.grpcUrls) entry.grpcUrls = c.grpcUrls.map(u => ({ http: u }));
  }

  if (c.transactionOverrides) entry.transactionOverrides = c.transactionOverrides;

  return entry;
}

function main() {
  if (!fs.existsSync(CHAINS_DIR)) {
    console.error(`[build-agent-config] no chains/ dir at ${CHAINS_DIR}`);
    process.exit(1);
  }
  const dirs = fs.readdirSync(CHAINS_DIR, { withFileTypes: true })
    .filter(e => e.isDirectory() && !e.name.startsWith('_') && !e.name.startsWith('.'))
    .map(e => path.join(CHAINS_DIR, e.name));

  const chains = {};
  let count = 0;
  for (const d of dirs) {
    const c = readChain(d);
    if (!c) {
      console.error(`[build-agent-config] skipped ${d} (no chain.yaml or missing 'key:' field)`);
      continue;
    }
    chains[c.key] = toAgentEntry(c);
    count++;
  }

  const out = {
    _comment: 'Auto-generated by tools/build_agent_config.mjs from chains/*/chain.yaml. Do not edit directly — your changes will be overwritten on the next drive.sh up. To customise, edit the relevant chain.yaml.',
    chains,
    defaultRpcConsensusType: 'fallback',
  };

  fs.mkdirSync(path.dirname(OUT_PATH), { recursive: true });
  fs.writeFileSync(OUT_PATH, JSON.stringify(out, null, 2) + '\n');
  console.error(`[build-agent-config] wrote ${count} chain(s) to ${OUT_PATH}`);
}

main();
