#!/usr/bin/env node
// build_relayer_env.mjs — generate relayer/.env-chains from
// chains/*/chain.yaml + relayer/.env.
//
// The relayer's per-chain signer keys + per-chain custom RPCs are
// named `HYP_CHAINS_<KEY_UPPER>_SIGNER_KEY` and
// `HYP_CHAINS_<KEY_UPPER>_CUSTOMRPCURLS`. Docker Compose can't pull
// those out of a dict, so we pre-render them into an env_file that
// the relayer compose loads.
//
// Inputs:
//   chains/*/chain.yaml — list of chains
//   relayer/.env        — operator's per-chain SIGNER_KEY_<KEY> values
//                          and optional <KEY>_RPC overrides
//
// Output:
//   relayer/.env-chains — HYP_CHAINS_<KEY>_SIGNER_TYPE/KEY/CUSTOMRPCURLS lines
//
// drive.sh runs this on every `up`, so adding a chain (or rotating a
// signer key) is just: edit, drive.sh up.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { parse as parseYaml } from 'yaml';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const KIT_ROOT = path.resolve(__dirname, '..');
const CHAINS_DIR = path.join(KIT_ROOT, 'chains');
const RELAYER_DIR = path.join(KIT_ROOT, 'relayer');
const ENV_PATH = path.join(RELAYER_DIR, '.env');
const OUT_PATH = path.join(RELAYER_DIR, '.env-chains');

function parseDotEnv(p) {
  if (!fs.existsSync(p)) return {};
  const out = {};
  for (const raw of fs.readFileSync(p, 'utf8').split('\n')) {
    const line = raw.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq < 0) continue;
    const k = line.slice(0, eq).trim();
    let v = line.slice(eq + 1).trim();
    if ((v.startsWith('"') && v.endsWith('"')) || (v.startsWith("'") && v.endsWith("'"))) {
      v = v.slice(1, -1);
    }
    out[k] = v;
  }
  return out;
}

function keyUpper(k) {
  return k.toUpperCase().replace(/-/g, '_');
}

function listChains() {
  const dirs = fs.readdirSync(CHAINS_DIR, { withFileTypes: true })
    .filter(e => e.isDirectory() && !e.name.startsWith('_') && !e.name.startsWith('.'));
  const out = [];
  for (const e of dirs) {
    const yp = path.join(CHAINS_DIR, e.name, 'chain.yaml');
    if (!fs.existsSync(yp)) continue;
    const c = parseYaml(fs.readFileSync(yp, 'utf8'));
    if (c && c.key) out.push(c);
  }
  return out;
}

function main() {
  const env = parseDotEnv(ENV_PATH);
  const chains = listChains();

  // Resolve RELAY_CHAINS — comma-separated list of chain keys this
  // relayer will deliver to. If unset, default to every preset chain.
  const relayChains = (env.RELAY_CHAINS || chains.map(c => c.key).join(','))
    .split(',').map(s => s.trim()).filter(Boolean);

  const lines = [
    '# Generated by tools/build_relayer_env.mjs — DO NOT EDIT.',
    '# Edit relayer/.env (operator-local) and chains/*/chain.yaml (presets)',
    '# instead, then re-run drive.sh up.',
    '',
  ];

  // For every chain the relayer is configured to deliver to:
  //   - signer type + key (from SIGNER_KEY_<KEY> in .env, written by 01_setup.sh)
  //   - custom RPC URL = stagger sidecar (the relayer routes through it)
  //   - optional per-host private RPC override (forwarded to the agent)
  for (const k of relayChains) {
    const KU = keyUpper(k);
    const signerKey = env[`SIGNER_KEY_${KU}`] || '';
    const rpcOverride = env[`${KU}_RPC`] || '';

    lines.push(`HYP_CHAINS_${KU}_SIGNER_TYPE=hexKey`);
    lines.push(`HYP_CHAINS_${KU}_SIGNER_KEY=${signerKey}`);
    lines.push(`HYP_CHAINS_${KU}_CUSTOMRPCURLS=http://stagger-sidecar:8545/${k}`);
    if (rpcOverride) {
      lines.push(`HYP_CHAINS_${KU}_RPCURLS_0_HTTP=${rpcOverride}`);
    }
    lines.push('');
  }

  fs.writeFileSync(OUT_PATH, lines.join('\n'));
  console.error(`[build-relayer-env] wrote ${relayChains.length} chain(s) to ${OUT_PATH}`);
}

main();
