#!/usr/bin/env node
// gen_registry.mjs — auto-generate chains/REGISTRY.md from every
// chains/*/chain.yaml. The registry is a human-readable table of
// supported chains with key facts (chainId, explorer, RPCs, mailbox
// address). Run on every push to main / before tagging.
//
// Usage:
//   node tools/gen_registry.mjs > chains/REGISTRY.md

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { parse as parseYaml } from 'yaml';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const CHAINS_DIR = path.resolve(__dirname, '..', 'chains');

function loadChains() {
  const out = [];
  for (const e of fs.readdirSync(CHAINS_DIR, { withFileTypes: true })) {
    if (!e.isDirectory() || e.name.startsWith('_') || e.name.startsWith('.')) continue;
    const yp = path.join(CHAINS_DIR, e.name, 'chain.yaml');
    if (!fs.existsSync(yp)) continue;
    const c = parseYaml(fs.readFileSync(yp, 'utf8'));
    if (c && c.key) out.push(c);
  }
  return out.sort((a, b) => a.key.localeCompare(b.key));
}

function row(c) {
  const explorer = c.blockExplorer ? `[scan](${c.blockExplorer})` : '—';
  const mailbox = c.hyperlane?.mailbox || '—';
  const mailboxShort = mailbox.startsWith('0x') ? mailbox.slice(0, 8) + '…' + mailbox.slice(-6) : mailbox;
  const rpcs = (c.rpcUrls || []).length;
  const finality = c.finality?.reorgPeriod ?? '?';
  return `| \`${c.key}\` | ${c.name || c.key} | ${c.chainId} | ${c.protocol || 'ethereum'} | ${rpcs} | ${finality} | \`${mailboxShort}\` | ${explorer} |`;
}

const chains = loadChains();
const lines = [
  '# Chain Registry',
  '',
  '<!-- Auto-generated by tools/gen_registry.mjs from chains/*/chain.yaml. -->',
  '<!-- DO NOT EDIT MANUALLY — your changes will be overwritten. To change a chain entry, edit chains/<key>/chain.yaml. -->',
  '',
  `**${chains.length} chain(s) supported.** Each row corresponds to a directory under [\`chains/\`](.).`,
  '',
  '| Key | Name | chainId | Protocol | RPCs | reorgPeriod | Mailbox | Explorer |',
  '|-----|------|---------|----------|------|-------------|---------|----------|',
];
for (const c of chains) lines.push(row(c));
lines.push('');
lines.push('## How to add a chain');
lines.push('');
lines.push('See [`../runbooks/ADD_CHAIN.md`](../runbooks/ADD_CHAIN.md) for the full process. Short version:');
lines.push('');
lines.push('1. Deploy Hyperlane core on your chain (`deployer/_run_deploy.sh deploy_evm_core.mjs`).');
lines.push('2. `cp -r chains/_template chains/<your-key>` — fill in `chain.yaml`.');
lines.push('3. Open a PR. CI runs `verify_bridge_health.mjs --chain <your-key>` to confirm declared addresses are real on-chain.');
lines.push('4. Core team reviews + merges. Existing operators `git pull && drive.sh up` to pick up the new chain.');
process.stdout.write(lines.join('\n') + '\n');
